import 'package:powersync/powersync.dart';

/// PowerSync local SQLite schema — engine-level (universal) table names.
/// See docs/NAMING.md for the contract.
///
/// PowerSync auto-adds the `id` column as TEXT PRIMARY KEY on every
/// table; don't declare it explicitly. Booleans serialize to INTEGER
/// (0/1); dates/timestamps to TEXT (ISO 8601); jsonb to TEXT (raw JSON).
const appSchema = Schema([
  Table('spaces', [
    Column.text('name'),
    Column.text('slug'),
    Column.text('settings'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('members', [
    Column.text('space_id'),
    Column.text('display_name'),
    Column.text('role'),
    Column.text('avatar_url'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('groups', [
    Column.text('space_id'),
    Column.text('name'),
    Column.text('age_range'),
    Column.text('color'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('enrollments', [
    Column.text('member_id'),
    Column.text('group_id'),
    Column.text('space_id'),
    Column.text('role'),
    Column.text('created_at'),
  ]),
  Table('subjects', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('dob'),
    Column.text('photo_url'),
    Column.text('allergies'),
    Column.text('notes'),
    Column.text('capabilities'),
    // Per-kid drop-off / pickup windows. Stored as ISO-8601 time
    // strings ('HH:mm:ss') because PowerSync's local SQLite doesn't
    // have a native TIME type. Parsed client-side.
    Column.text('dropoff_window_start'),
    Column.text('dropoff_window_end'),
    Column.text('pickup_window_start'),
    Column.text('pickup_window_end'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('guardians', [
    Column.text('space_id'),
    Column.text('user_id'),
    Column.text('name'),
    Column.text('relationship'),
    Column.text('phone'),
    Column.text('email'),
    Column.integer('authorized_for_pickup'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('subject_guardians', [
    Column.text('subject_id'),
    Column.text('guardian_id'),
    Column.text('space_id'),
    Column.integer('is_primary'),
    Column.text('created_at'),
  ]),
  Table('attendance_records', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('subject_id'),
    Column.text('date'),
    Column.text('status'),
    Column.text('notes'),
    Column.text('recorded_by'),
    Column.text('recorded_at'),
    Column.text('updated_at'),
  ]),
  Table('invites', [
    Column.text('space_id'),
    Column.text('email'),
    Column.text('code'),
    Column.text('role'),
    Column.text('subject_id'),
    Column.text('capabilities'),
    Column.text('created_by'),
    Column.text('created_at'),
    Column.text('expires_at'),
    Column.text('accepted_at'),
    Column.text('accepted_by'),
  ]),
  Table('group_members', [
    Column.text('group_id'),
    Column.text('member_id'),
    Column.text('space_id'),
    Column.text('role_in_group'),
    Column.text('assigned_at'),
  ]),
  Table('entries', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('subject_id'),
    Column.text('kind'),
    Column.text('text'),
    Column.text('photo_url'),
    Column.text('details'),
    Column.text('recorded_by'),
    Column.text('recorded_at'),
    Column.text('updated_at'),
  ]),
  Table('vehicles', [
    Column.text('space_id'),
    Column.text('name'),
    Column.text('make'),
    Column.text('model'),
    Column.integer('year'),
    Column.text('license_plate'),
    Column.text('color'),
    Column.text('photo_url'),
    Column.text('notes'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('vehicle_logs', [
    Column.text('space_id'),
    Column.text('vehicle_id'),
    Column.text('kind'),
    Column.text('driver_member_id'),
    Column.integer('odometer'),
    Column.text('fuel_level'),
    Column.text('items'),
    Column.text('notes'),
    Column.text('body_damage_notes'),
    Column.text('created_at'),
  ]),
  Table('member_certifications', [
    Column.text('space_id'),
    Column.text('member_id'),
    Column.text('cert_key'),
    Column.text('issued_at'),
    Column.text('expires_at'),
    Column.text('notes'),
    Column.text('document_url'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('attachments', [
    Column.text('space_id'),
    Column.text('entity_kind'),
    Column.text('entity_id'),
    Column.text('url'),
    Column.text('thumb_url'),
    Column.text('mime_type'),
    Column.text('caption'),
    Column.integer('sort_order'),
    Column.text('uploaded_by'),
    Column.text('taken_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('survey_responses', [
    Column.text('space_id'),
    Column.text('template_id'),
    Column.text('subject_id'),
    Column.text('status'),
    Column.text('recorded_by'),
    Column.text('answers'),
    Column.text('started_at'),
    Column.text('completed_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('dismissed_insights', [
    Column.text('space_id'),
    Column.text('member_id'),
    Column.text('insight_id'),
    Column.text('dismissed_until'),
    Column.text('created_at'),
  ]),
  Table('captures', [
    Column.text('space_id'),
    Column.text('author_id'),
    Column.text('body'),
    Column.text('status'),
    Column.text('promoted_to_kind'),
    Column.text('promoted_to_id'),
    Column.text('promoted_subject_id'),
    Column.text('processed_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('tasks', [
    Column.text('space_id'),
    Column.text('author_id'),
    Column.text('subject_id'),
    Column.text('body'),
    Column.text('status'),
    Column.text('due_at'),
    Column.text('completed_by'),
    Column.text('completed_at'),
    Column.text('created_from_capture_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('messages', [
    Column.text('space_id'),
    Column.text('subject_id'),
    Column.text('guardian_id'),
    Column.text('sender_kind'),
    Column.text('sender_member_id'),
    Column.text('sender_guardian_id'),
    Column.text('body'),
    Column.text('read_at'),
    // JSONB on the server side; stored as raw JSON string locally.
    // Per-guardian read-state for co-parent / multi-guardian threads.
    Column.text('read_by_guardian_ids'),
    Column.text('created_at'),
  ]),
  Table('exports', [
    Column.text('space_id'),
    Column.text('author_id'),
    Column.text('template_id'),
    Column.text('template_version'),
    Column.text('subject_id'),
    Column.text('group_id'),
    Column.text('status'),
    Column.text('format'),
    Column.text('storage_path'),
    Column.text('snapshot_json'),
    Column.text('note'),
    Column.text('generated_at'),
    Column.text('sent_at'),
    Column.text('archived_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('export_recipients', [
    Column.text('export_id'),
    Column.text('space_id'),
    Column.text('kind'),
    Column.text('guardian_id'),
    Column.text('member_id'),
    Column.text('external_label'),
    Column.text('external_email'),
    Column.text('channel'),
    Column.text('state'),
    Column.text('state_detail'),
    Column.text('sent_at'),
    Column.text('read_at'),
    Column.text('created_at'),
  ]),

  // ---- Camp scheduling ----------------------------------------------------
  // See supabase/migrations/20260519000003_camp_scheduling.sql.
  Table('locations', [
    Column.text('space_id'),
    Column.text('name'),
    Column.text('notes'),
    Column.integer('capacity'),
    Column.integer('is_outdoor'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('activities', [
    Column.text('space_id'),
    Column.text('owner_member_id'),
    Column.text('name'),
    Column.text('description'),
    Column.text('default_location_id'),
    Column.integer('default_duration_minutes'),
    Column.text('supplies'),
    Column.integer('age_min'),
    Column.integer('age_max'),
    Column.integer('max_capacity'),
    Column.integer('is_outdoor'),
    Column.text('indoor_alt_activity_id'),
    Column.text('capabilities'),
    Column.text('archived_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('schedule_blocks', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('date'),
    Column.text('start_at'),
    Column.text('end_at'),
    Column.text('activity_id'),
    Column.text('lead_member_id'),
    // Per-day override — when the originally-planned lead is out, the
    // director sets this to the cover member. See migration
    // 20260520000002_lead_substitutes.sql.
    Column.text('lead_substitute_member_id'),
    Column.text('location_override_id'),
    Column.text('kind'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('trip_logistics', [
    Column.text('space_id'),
    Column.text('schedule_block_id'),
    Column.text('destination'),
    Column.text('destination_address'),
    Column.text('departure_at'),
    Column.text('return_at'),
    Column.integer('requires_permission_slip'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('trip_vehicles', [
    Column.text('space_id'),
    Column.text('trip_logistics_id'),
    Column.text('vehicle_id'),
    Column.text('driver_member_id'),
    Column.text('manifest'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('permission_slips', [
    Column.text('space_id'),
    Column.text('subject_id'),
    Column.text('trip_logistics_id'),
    Column.text('signer_guardian_id'),
    Column.text('signer_name'),
    Column.text('signed_at'),
    Column.text('source_url'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('headcounts', [
    Column.text('space_id'),
    Column.text('schedule_block_id'),
    Column.text('checkpoint_label'),
    Column.integer('count'),
    Column.integer('expected_count'),
    Column.text('taken_by_member_id'),
    Column.text('taken_at'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
]);
