import 'package:powersync/powersync.dart';

/// PowerSync local SQLite schema — engine-level (universal) table names.
/// See docs/NAMING.md for the contract.
///
/// PowerSync auto-adds the `id` column as TEXT PRIMARY KEY on every
/// table; don't declare it explicitly. Booleans serialize to INTEGER
/// (0/1); dates/timestamps to TEXT (ISO 8601); jsonb to TEXT (raw JSON).
const appSchema = Schema([
  Table('spaces', [
    Column.text('name'),
    Column.text('slug'),
    Column.text('settings'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('members', [
    Column.text('space_id'),
    Column.text('display_name'),
    Column.text('role'),
    Column.text('avatar_url'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('groups', [
    Column.text('space_id'),
    Column.text('name'),
    Column.text('age_range'),
    Column.text('color'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('enrollments', [
    Column.text('member_id'),
    Column.text('group_id'),
    Column.text('space_id'),
    Column.text('role'),
    Column.text('created_at'),
  ]),
  Table('subjects', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('dob'),
    Column.text('photo_url'),
    Column.text('allergies'),
    Column.text('notes'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('guardians', [
    Column.text('space_id'),
    Column.text('user_id'),
    Column.text('name'),
    Column.text('relationship'),
    Column.text('phone'),
    Column.text('email'),
    Column.integer('authorized_for_pickup'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('subject_guardians', [
    Column.text('subject_id'),
    Column.text('guardian_id'),
    Column.text('space_id'),
    Column.integer('is_primary'),
    Column.text('created_at'),
  ]),
  Table('attendance_records', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('subject_id'),
    Column.text('date'),
    Column.text('status'),
    Column.text('notes'),
    Column.text('recorded_by'),
    Column.text('recorded_at'),
    Column.text('updated_at'),
  ]),
  Table('invites', [
    Column.text('space_id'),
    Column.text('email'),
    Column.text('code'),
    Column.text('role'),
    Column.text('subject_id'),
    Column.text('capabilities'),
    Column.text('created_by'),
    Column.text('created_at'),
    Column.text('expires_at'),
    Column.text('accepted_at'),
    Column.text('accepted_by'),
  ]),
  Table('group_members', [
    Column.text('group_id'),
    Column.text('member_id'),
    Column.text('space_id'),
    Column.text('role_in_group'),
    Column.text('assigned_at'),
  ]),
  Table('entries', [
    Column.text('space_id'),
    Column.text('group_id'),
    Column.text('subject_id'),
    Column.text('kind'),
    Column.text('text'),
    Column.text('photo_url'),
    Column.text('details'),
    Column.text('recorded_by'),
    Column.text('recorded_at'),
    Column.text('updated_at'),
  ]),
  Table('vehicles', [
    Column.text('space_id'),
    Column.text('name'),
    Column.text('make'),
    Column.text('model'),
    Column.integer('year'),
    Column.text('license_plate'),
    Column.text('color'),
    Column.text('photo_url'),
    Column.text('notes'),
    Column.text('capabilities'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('vehicle_logs', [
    Column.text('space_id'),
    Column.text('vehicle_id'),
    Column.text('kind'),
    Column.text('driver_member_id'),
    Column.integer('odometer'),
    Column.text('fuel_level'),
    Column.text('items'),
    Column.text('notes'),
    Column.text('body_damage_notes'),
    Column.text('created_at'),
  ]),
  Table('member_certifications', [
    Column.text('space_id'),
    Column.text('member_id'),
    Column.text('cert_key'),
    Column.text('issued_at'),
    Column.text('expires_at'),
    Column.text('notes'),
    Column.text('document_url'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
]);
